version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - $API_PORT:$API_PORT
    networks:
      - api
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    env_file:
      - .env
    command: "uvicorn cardiospike.api.app:app --port $API_PORT --host 0.0.0.0"
  web:
    container_name: worker
    build:
      context: .
    ports:
      - $WEB_PORT:$WEB_PORT
    networks:
      - api
    volumes:
      - type: bind
        source: ./data
        target: /cardiospike/data/
    env_file:
      - .env
    command: "gunicorn --workers=5 --threads=2 --bind 0.0.0.0:$WEB_PORT cardiospike.web.app:app"

networks:
  api:
