version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - $API_PORT:$API_PORT
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    env_file:
      - .env
    command: "uvicorn cardiospike.api.app:app --port $API_PORT --host 0.0.0.0"
#  web:
#    container_name: worker
#    build:
#      context: .
#    ports:
#      - 6006:6006
#    volumes:
#      - type: bind
#        source: ./data
#        target: /cardiospike/data/
#      - type: bind
#        source: ./data/submissions
#        target: /cardiospike/data/submissions
#      - type: bind
#        source: ./data/model-checkpoints
#        target: /cardiospike/data/model-checkpoints
