version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - $API_PORT:$API_PORT
    environment:
      - API_PORT=5000
    networks:
      - api
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    env_file:
      - .env
    command: "uvicorn cardiospike.api.app:app --port $API_PORT --host 0.0.0.0"
  web:
    container_name: web
    depends_on:
      - api
    build:
      context: .
    ports:
      - $WEB_PORT:$WEB_PORT
    environment:
      - API_HOST=api
      - WORKERS=$WORKERS
      - THREADS=$THREADS
    networks:
      - api
      - front
    volumes:
      - type: bind
        source: ./data
        target: /cardiospike/data/
    env_file:
      - .env
    command: "gunicorn --workers=$WORKERS --threads=$THREADS cardiospike.web.app:app --bind 0.0.0.0:$WEB_PORT"

networks:
  api:
    driver: bridge
  front:
