version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - $API_PORT:$API_PORT
    networks:
      - api
    volumes:
      - type: bind
        source: ./data
        target: /cardiospike/data/
      - type: bind
        source: ./cardiospike
        target: /cardiospike/cardiospike/
    env_file:
      - .env
    command: "uvicorn cardiospike.api.app:app --port $API_PORT --host 0.0.0.0 --reload"

  web:
    container_name: web
    build:
      context: .
    ports:
      - $WEB_PORT:$WEB_PORT
    environment:
      - API_HOST=api
      - WORKERS=2
      - THREADS=2
      - FLASK_DEBUG=1
    networks:
      - api
      - front
    volumes:
      - type: bind
        source: ./data
        target: /cardiospike/data/
      - type: bind
        source: ./cardiospike
        target: /cardiospike/cardiospike/
    env_file:
      - .env
    command: "gunicorn --workers=$WORKERS --threads=$THREADS cardiospike.web.app:app --bind 0.0.0.0:$WEB_PORT --reload"

networks:
  api:
    driver: bridge
  front:
