name: GitHub Actions Demo

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ./venv
          installer-parallel: true
      - name: Install own dependencies
        run: |
          poetry install
      - name: Run unit tests
        run: |
          python -m pytest .
